debril_feed_io_feed:
    resource: "@DebrilFeedIoBundle/Resources/config/routing/feed.yml"
    prefix:   /feed

debril_feed_io_crud_feed:
    resource: "@DebrilFeedIoBundle/Resources/config/routing/crud/feed.yml"
    prefix:   /crud/feed
    
debril_feed_io_crud_item:
    resource: "@DebrilFeedIoBundle/Resources/config/routing/crud/item.yml"
    prefix:   /crud/item
    
debril_feed_io_crud_media:
    resource: "@DebrilFeedIoBundle/Resources/config/routing/crud/media.yml"
    prefix:   /crud/media
    
feedio_stream:
    path: /stream/{format}/{id}
    defaults: { _controller: DebrilFeedIoBundle:Stream:index, format: 'rss' }
    requirements: { "format": "rss|atom" }
    
feedio_rss:
    path: /rss/{id}
    defaults: { _controller: DebrilFeedIoBundle:Stream:index, "format": 'rss', "id": null }
    
feedio_atom:
    path: /atom/{id}
    defaults: { _controller: DebrilFeedIoBundle:Stream:index, "format": 'atom', "id": null }

feedio_mock:
    path: /mock/rss/{id}
    defaults: { _controller: DebrilFeedIoBundle:Stream:index, "format": 'rss', "id": null }
