feed_add:
    path:     /add
    defaults: { _controller: DebrilFeedIoBundle:Feed:add }

feed_new:
    path:     /new
    defaults: { _controller: DebrilFeedIoBundle:Feed:new }

feed_show:
    path:     /{id}/show
    defaults: { _controller: DebrilFeedIoBundle:Feed:show }

feed_edit:
    path:     /{id}/edit
    defaults: { _controller: DebrilFeedIoBundle:Feed:edit }

feed_index:
    path:     /
    defaults: { _controller: DebrilFeedIoBundle:Feed:index }

feed_update:
    path:     /{id}/update
    defaults: { _controller: DebrilFeedIoBundle:Feed:update }
